language: python
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.6
      env: TOXENV=py36
    - env: TOXENV=pep8
install:
  - pip install -r test-requirements.txt
script:
  - tox -e "$TOXENV"
deploy:
  provider: pypi
  user: dcaro
  distribution: sdist
  password:
    secure: PZ0DEiZJqqKct+PzhHf828DEj8yFEW13rJ18ZywwMUtYjNtSoxEa/2mMommbDkIWQxAT0N3t0QoQu71tzf6Aw3zuFaumxuqMCI+3NZo/ZztY9hBWlwkTu4LzWQi9G116GmPnXvcagTLWpqgB2YXnS4QmEHcz6QyH2heHaEt6rQY=
  on:
    branch: master
    python: '2.7'
